still looking for it

diff --git a/.github/workflows/cuda.yml b/.github/workflows/cuda.yml
--- a/.github/workflows/cuda.yml
+++ b/.github/workflows/cuda.yml
@@ -50,7 +50,7 @@ jobs:
         path: amrex
     - name: Build & Install
       run: |
-        locate "cufft.h"
+        find / -name "cufft.h" -print || echo "Cannot find cufft.h"
         cd exec/multispec
         export PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
         export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
