all the cudas

diff --git a/.github/workflows/cuda.yml b/.github/workflows/cuda.yml
--- a/.github/workflows/cuda.yml
+++ b/.github/workflows/cuda.yml
@@ -50,10 +50,11 @@ jobs:
         path: amrex
     - name: Build & Install
       run: |
-        find / -name "cufft.h" -print || echo "Cannot find cufft.h"
-        cd exec/multispec
         export PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
-        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
+        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
+        export LD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
+        find / -name "cufft.h" -print 2>/dev/null || echo "Cannot find cufft.h"
+        cd exec/multispec
         which nvcc || echo "nvcc not in PATH!"
         nvcc test.cu -lcufft -o justTest
         make -j2 VERBOSE=1 USE_MPI=TRUE USE_CUDA=TRUE USE_OMP=FALSE DIM=3 TINY_PROFILE=FALSE
